base_name: SLAP2-to-spectrograms
processing_inputs:
  - source: s3://umpg-uppm-prod-music-assets
    input_name: audio
    destination: /opt/ml/processing/input
processing_outputs:
  - destination: s3://maml-aimcdt/datasets/SLAP2/upmm2
    output_name: npy
    source: /opt/ml/processing/output
processor:
  image_uri: 427750820708.dkr.ecr.us-east-1.amazonaws.com/julien_simple_scripts:latest
  instance_count: 10
  role: maml-aimcdt-sagemaker
  instance_type: ml.g5.4xlarge
  volume_size_in_gb: 1024
  entrypoint: [python, scripts/to_spectrogram.py]
  tags:
    - Key: Project
      Value: maml-feature-extraction
    - Key: Application-Name
      Value: MAML